version: '3'
services:
  broker:
    image: pactfoundation/pact-broker:latest
    environment:
      PACT_BROKER_LOG_LEVEL: DEBUG
      PACT_BROKER_PORT: 9292
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http https"
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: "/.*/"
    expose:
      - 9292
    ports:
      - 19292:9292

  resource:
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      TEST_PACT_BROKER_URL: http://broker:9292
    links:
      - broker
    depends_on:
      - broker
    volumes:
    - .:/resource
