version: 2
jobs:
  run-tests:
    docker:
      - image: golang:latest
        name: resource
      - image: pactfoundation/pact-broker:latest
        name: broker
        environment:
          PACT_BROKER_LOG_LEVEL: DEBUG
          PACT_BROKER_PORT: 9292
          PACT_BROKER_DATABASE_ADAPTER: sqlite
          PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http https"
          PACT_BROKER_WEBHOOK_HOST_WHITELIST: "/.*/"

    environment:
      TEST_PACT_BROKER_URL: http://broker:9292

    working_directory: /resource
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test-short
      - run:
          name: Build binaries
          command: make build
      - run:
          name: Run integration tests
          command: make test-integration

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-tests
